# Name the node stage "builder"
FROM node:12 as builder

# Set working directory
WORKDIR /app
# Copy all files from current directory to working dir in image
COPY ./frontend/package.json ./frontend/yarn.lock ./
RUN yarn cache clean && yarn --update-checksums
COPY ./frontend ./
# install node modules and build assets
RUN yarn build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./frontend/nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
