# Name the node stage "builder"
FROM node:12 as builder

# Set working directory
WORKDIR /app
# Copy all files from current directory to working dir in image
COPY ./frontend/package.json ./frontend/yarn.lock ./
RUN yarn cache clean && yarn --update-checksums
COPY ./frontend ./
# install node modules and build assets
RUN yarn build

# nginx state for serving content
FROM nginx:alpine
# Set working directory to nginx asset directory
WORKDIR /usr/share/nginx/html
# Remove default nginx static assets
RUN rm -rf ./*
COPY /app/nginx/nginx.conf /etc/nginx/conf.d
# Copy static assets from builder stage
COPY --from=builder /app/dist .
# Containers run nginx with global directives and daemon off
EXPOSE 3001
ENTRYPOINT ["nginx", "-g", "daemon off;"]