name: build-frontend

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - Dockerfile-frontend
      - .github/workflows/deploy-frontend.yml

env:
  IMAGE_NAME: 2110521-2563-1-software-architecture/moonmacrosystem/mm-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.10
        uses: actions/setup-node@v1
        with:
          node-version: "13.10"
      - name: Install yarn and run unittest
        run: |
          cd frontend
          yarn
        env:
          CI: true
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 2110521-2563-1-software-architecture/moonmacrosystem/mm-frontend
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile-frontend
          tags: latest
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Deploy docker to the host
        run: |
          if ! test -z $(docker ps -a -q --filter ancestor=$CONTAINER_NAME); then docker stop $(docker ps -a -q --filter ancestor=$CONTAINER_NAME); fi
          docker login docker.pkg.github.com -u $DOCKER_USERNAME -p $GITHUB_TOKEN
          docker pull $CONTAINER_NAME
          docker run -dit -p 3001:3001 $CONTAINER_NAME
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER_NAME: docker.pkg.github.com/2110521-2563-1-software-architecture/moonmacrosystem/mm-frontend:latest
