name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.10
        uses: actions/setup-node@v1
        with:
          node-version: "13.10"
      - name: Install yarn and run unittest
        run: |
          cd backend
          yarn
        env:
          CI: true
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 2110521-2563-1-Software-Architecture/MoonMacrosystem/mm-backend
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Deploy docker to the host
        run: |
          if ! test -z $(docker ps -a -q); then docker stop $(docker ps -a -q); fi
          docker login docker.pkg.github.com -u $docker_username -p $github_token
          docker pull docker.pkg.github.com/2110521-2563-1-software-architecture/moonmacrosystem/mm-backend:latest
          docker run -dit -p 80:5420 docker.pkg.github.com/2110521-2563-1-software-architecture/moonmacrosystem/mm-backend:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
